### ISSUE TITLE
Tracing SSM Parameter Store reload

### ISSUE THREAD

**Issue by morquan** [aws/aws-xray-sdk-dotnet#103]
Greetings.

I'm trying to use the XRay SDK in combination with SSM Parameter Store. I have registered XRay for all SDK services (`AWSSDKHandler.RegisterXRayForAllServices()`. I have SSM configured to reload periodically (`configurationBuilder.AddSystemsManager("...", TimeSpan.FromMinutes(1))`).

Each time the SSM configuration provider tries to reload, I'm seeing a message like this:

```
TraceContextImpl 834|2019-09-16T15:36:02.621Z|ERROR|Cannot get entity while processing AWS SDK request --> Amazon.XRay.Recorder.Core.Exceptions.EntityNotAvailableException: Entity doesn't exist in AsyncLocal
at Amazon.XRay.Recorder.Core.Internal.Context.AsyncLocalContextContainer.GetEntity()
at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineHandler.ProcessBeginRequest(IExecutionContext executionContext)
```

Is this scenario supported? It looks to me like some part of the SDK is failing to begin a segment for this operation.

Thanks for your time.

**Comment by morquan** [comment]
Thanks for the response! That all makes sense and aligns with my understanding as well.

The application in question is an ASP.NET Core MVC app (non-Lambda). 

For now I've disabled configuration reload to avoid the error. I could live without that activity being traced if necessary - I'd rather keep enabled.

**Comment by yogiraj07** [comment]
Thanks for the response. 
1. Can you add `AWSSDKHandler.RegisterXRayForAllServices()` after `(configurationBuilder.AddSystemsManager("...", TimeSpan.FromMinutes(1))` code logic.  `AWSSDKHandler.RegisterXRayForAllServices()` traces all instances of AWS SDK created after this instrumentation. I wonder if this helps in not tracing the reload call made by SSM.
2. If step 1 doesn't work, you would need to add per client type [instrumentation](https://github.com/aws/aws-xray-sdk-dotnet/tree/master#trace-aws-sdk-request-net-and-net-core--nuget), for example - `AWSSDKHandler.RegisterXRay<IAmazonDynamoDB>();`. This will trace only Amazon DynamoDB client instances.

In order to ease user experience, I think, we should add an API that takes a list of type of . AmazonServiceClient that should *NOT* be traced.

Best,
Yogi

**Comment by morquan** [comment]
I'm already doing #1 - `AWSSDKHandler.RegisterXRayForAllServices()` is called in `Startup.ConfigureServices` while `configurationBuilder.AddSystemsManager()` is called prior to that during the host building process.

Thanks for your suggestion for a workaround. A blocklist style approach would be nice, I agree. That said, I honestly don't know what service client types are in use because I'm not using them myself - I'm just using the various official AWS packages that integrate with ASP.NET Core:

Amazon.AspNetCore.DataProtection.SSM
Amazon.Extensions.Configuration.SystemsManager
AWS.Logger.AspNetCore
AWSXRayRecorder.Handlers.AspNetCore

I'd really expect to be able to use these packages in concert successfully, given I've followed their respective setup steps correctly, which I believe I have.

In addition to the issue with SSM reload, it appears that there's a similar issue with the Amazon.AspNetCore.DataProtection.SSM package; I get the same error from that, on startup. 

I understand that these may be managed by different teams at AWS, but it would be great to see a more cohesive experience. I could live without XRay tracing info for configuration reloads and data protection keyring management calls, but it would also still be useful information, if they worked.

Thanks for your help.

**Comment by morquan** [comment]
In case this helps, here's the error I'm seeing from the XRay SDK interfering with Amazon.AspNetCore.DataProtection.SSM. I've had to stop using `RegisterXRayForAllServices` for the time being.

> [Error] Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider: [48]: An error occurred while reading the key ring. Amazon.XRay.Recorder.Core.Exceptions.EntityNotAvailableException: Entity doesn't exist in AsyncLocal
> at Amazon.XRay.Recorder.Core.Internal.Context.AsyncLocalContextContainer.GetEntity()
> at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineHandler.ProcessBeginRequest(IExecutionContext executionContext)
> --- End of stack trace from previous location where exception was thrown ---
> at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineHandler.ProcessBeginRequest(IExecutionContext executionContext)
> at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineHandler.InvokeAsync[T](IExecutionContext executionContext)
> at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
> at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
> at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
> at Amazon.AspNetCore.DataProtection.SSM.SSMXmlRepository.GetAllElementsAsync()
> at Amazon.AspNetCore.DataProtection.SSM.SSMXmlRepository.GetAllElements()
> at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
> at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
> at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
> at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)

**Comment by benhilty** [comment]
Per the [Configuration docs](https://docs.aws.amazon.com/en_pv/xray/latest/devguide/xray-sdk-dotnet-configuration.html), it looks like you can set the environment variable `AWS_XRAY_CONTEXT_MISSING` to `LOG_ERROR` to prevent an exception from being thrown in these circumstances.

**Comment by willarmiros** [comment]
Apologies for not corresponding on this issue for some time. The workaround provided by @benhilty is the recommended approach for preventing this runtime exception. Since these requests are happening on a background thread and not part of handling a user request, there is no guarantee the necessary context to trace these requests will be available. It is therefore recommended to just use `IGNORE_ERROR` since these background requests would only add noise to the real requests.

A longer term solution would be to provide a deny-list that customers could use to prevent instrumentation for certain downstream services/endpoints, like this SSM background reload service.

**Comment by OlegKrymskyi** [comment]
Got the same problem. Here is my code:
`
// Program.cs
Host.CreateDefaultBuilder(args)
                .UseLamar()
                .ConfigureAppConfiguration((context, builder) =>
                {
                    builder.AddSystemsManager(configureSource =>
                    {
                        // Parameter Store prefix to pull configuration data from.
                        configureSource.Path = $"{ParametersStorePath}/{context.HostingEnvironment.EnvironmentName}";

                        // Reload configuration data every 5 minutes.
                        configureSource.ReloadAfter = TimeSpan.FromMinutes(ParametersStoreRefreshTimeInMinutes);

                        // Configure if the configuration data is optional.
                        configureSource.Optional = false;

                        // Implement custom parameter process, which transforms Parameter Store names into
                        // names for the .NET Core configuration system.
                        configureSource.ParameterProcessor = new AmazonStoreParameterProcessor();

                        // Throw exception;
                        configureSource.OnLoadException += (errorContext) => throw errorContext.Exception;
                    });

// Startup.cs
AWSSDKHandler.RegisterXRayForAllServices();
`
As you can see, SystemsManager added as a source of the configuration, and configuration has to be reloaded each N mins.
After the start up everything is fine. All params would be loaded. However, in N minutes separate thread would try to reload config, but because we are executing this code as web application in asp.net, XRay would try to get HTTPContext or some other context, hard to say and it would fail with `EntityNotAvailableException("Entity doesn't exist in AsyncLocal");`. 

So, my theory is that because we are using XRay for the api call our of asp.net request handling, we are failing and parameters wont be loaded
