### ISSUE TITLE
AspNet Handler Exception without User Agent

### ISSUE THREAD

**Issue by mpetito-envative** [aws/aws-xray-sdk-dotnet#14]
There's a NullReferenceException when using the ASP.NET handler if the inbound HTTP request does not have a User-Agent header specified.  This is a simple fix if you need a PR.

https://github.com/aws/aws-xray-sdk-dotnet/blob/4ca2e77200f4b4f7d6f642049da42e0005b7227e/sdk/src/Handlers/AspNet/AWSXRayASPNET.cs#L174

```
Exception information: 
    Exception type: NullReferenceException 
    Exception message: Object reference not set to an instance of an object.
   at Amazon.XRay.Recorder.Handlers.AspNet.AWSXRayASPNET.ProcessRequestAttributes(HttpRequest request, Dictionary`2 requestAttributes)
   at Amazon.XRay.Recorder.Handlers.AspNet.AWSXRayASPNET.ProcessHTTPRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

```

**Comment by yogiraj07** [comment]
Hi @mpetito-envative ,
Thank you for reaching out to us. We appreciate you for submitting the pull request for fixing this issue.
I am merging your pull request.

Best,
Yogi
