### ISSUE TITLE
Hard to reproduce race condition in RulePoller and TargetPoller

### ISSUE THREAD

**Issue by jeffclary** [aws/aws-xray-sdk-dotnet#142]
Found in Version: 2.7.2

I am seeing intermittent null reference exceptions when using XRay in an test environment, specifically running XUnit tests of an API (using Microsoft.AspNetCore.TestHost.TestServer) in a GitLab pipeline.

The TestServer is stopping with this stack trace:

```
The active test run was aborted. Reason: Test host process crashed : Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
    at Amazon.XRay.Recorder.Core.Sampling.RulePoller.Start(Object state)
    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

I believe this snippet from RulePoller.cs contains the code with the problem:

```
        internal void Poll(IConnector connector)
        {
            _connector = connector;
            _timer = InitializeTimer();
        }

        private Timer InitializeTimer()
        {
            return new Timer(Start, null, 0, 0);
        }

        internal async void Start(Object state)
        {
            try
            {
                await RefreshCache();
            }
            catch (Exception e)
            {
                _logger.Error(e, "Encountered an exception while polling sampling rules.");
            }
            finally
            {
                _timer.Change(GetDelay(), 0); // Next invocation with jitter
            }
        }

```
When `Poll` is first called, `_timer` is null.  It calls `InitializeTimer` and assigns the returned value to `_timer`.  But `InitializeTimer` creates a new `System.Threading.Timer` that calls `Start` with zero delay.  `Start` dereferences `_timer` in its finally block, which is where I think the null reference is happening.  Depending how the threads are scheduled, that finally block could be reached before the assignment to `_timer` happens.

I cloned this repo and tried to create a unit test to reproduce this issue, to no avail.  I suspect this race condition resolves differently on different architectures, container environments, etc.  Even in my build pipeline it does not fail every time.

I have not observed it as a failure, but there is very similar code that would subject to the same kind of race condition in [TargetPoller.cs](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/Sampling/TargetPoller.cs).

I am willing to fork and create a pull request for this issue, but since I cannot reproduce it at will, I won't be able to write a unit test that proves my fix.  I'd like some guidance from contributors on how to proceed and whether a pull request would be considered for merging.

**Comment by srprash** [comment]
Hi @jeffclary 
I really appreciate your deep dive into the issue and presenting a possible root cause analysis. Please allow me some time to understand the issue and hopefully come up with a condition where we can reproduce it.
I'll post an update as soon as possible. 
Thanks! :)

**Comment by smclewin** [comment]
@srprash any progress on attempts to reproduce this behavior?

**Comment by srprash** [comment]
Hi @jeffclary and @smclewin 
I didn't have much success in coming up with a unit test to this condition deterministically. I do feel that `_timer.Change(GetDelay(), 0);` in the TimerCallback `Start` can very well be the cause of the null reference exception.

I think that instead of setting of the Timer right away, the `_timer` member variable should be initialized first and then it can be set off using `_timer.Change(0, 0)`. This would ensure that `_timer` is initialized before it is accessed in the `Start` thread.
Let me know your thoughts on this. I'll try to spend some more time on this.

**Comment by jeffclary** [comment]
@srprash, that was my exact thought for a fix, that is, construct the timer with an infinite `dueTime`, get it assigned to the `_timer` member, and *only then* set the `dueTime` to zero to cause it to trigger immediately.  You'll probably need to eliminate or at least change the `InitializeTimer` method to make this happen.  I'd probably just move the assignment of `_timer` into that method.

**Comment by srprash** [comment]
@jeffclary, this should do the trick!
I'll try to address this change as soon as possible. In the meantime, a PR is always welcome :)

**Comment by smclewin** [comment]
@srprash so far as we can tell the merged fix is not yet in a published version.  Is that the case?  Or is there a version of X-Ray we can pull into our projects that can address the race condition @jeffclary  reported?

**Comment by srprash** [comment]
Hi @smclewin . Right. We are due for a release very soon which will have this fix. I'll update the issue as soon as the new version is available. Please stay tuned.
Thanks.

**Comment by bitshop** [comment]
We also appear to be encountering this error, given the PR exists we didn't deep dive into it.  Any ETA on release or do you recommend we building from source as a work around? I see some other items are work in progress so assume it's not ready to publish (?)
Thanks.

**Comment by lupengamzn** [comment]
Hey @bitshop ,

The X-Ray .NET SDK v2.10.0 has been released.

https://www.nuget.org/packages?q=awsxrayrecorder
