### ISSUE TITLE
Entity doesn't exist in AsyncLocal -  .WithContextMissingStrategy(ContextMissingStrategy.LOG_ERROR) does not work

### ISSUE THREAD

**Issue by chazt3n** [aws/aws-xray-sdk-dotnet#162]
The following code still throws a runtime exception when tracing DbContexts/HttpClients/Sdk

```csharp
                    AWSXRayRecorder recorder = new AWSXRayRecorderBuilder()
                        .WithDaemonAddress(xrayDaemonAddress)
                        .WithContextMissingStrategy(ContextMissingStrategy.LOG_ERROR)
                        .Build();
                    AWSXRayRecorder.InitializeInstance(recorder: recorder);
                    AWSSDKHandler.RegisterXRayForAllServices();
                    builder.UseXRay(config[ApplicationName]);
```

Can there not be a guard that will simply create a segment if one is not found?

It seems better to simply have some tracing data that needs to be improved over time than crippling an application. But I am still ignorant on all things X-Ray. 

EDIT: setting AWS_XRAY_CONTEXT_MISSING does nothing

**Comment by willarmiros** [comment]
Hi @chazt3n,

You need to start a [segment](https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-segments) before making requests using an instrumented HTTP client. You can either manually begin segments or, if using a web app framework, have the SDK [automatically create segments for incoming requests](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-dotnet-messagehandler.html). The instrumented HTTP client will attempt to begin a subsegment, and if there is no parent segment for it to attach to a runtime exception will be thrown. 

That's very strange that a runtime error is still thrown after setting the context missing strategy to log error. Setting it to log error should guarantee runtime exceptions are not thrown and the errors are simply logged instead. Can you post the stacktrace and more detailed reproduction code if the exception is being thrown even after setting LOG_ERROR?

**Comment by chazt3n** [comment]
>   at Amazon.XRay.Recorder.Core.Internal.Context.AsyncLocalContextContainer.GetEntity()
   at Amazon.XRay.Recorder.Core.AWSXRayRecorderImpl.GetEntity()
   at Amazon.XRay.Recorder.Handlers.EntityFramework.EFInterceptor.ProcessCommandError(CommandErrorEventData eventData)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.XRay.Recorder.Core.Internal.Context.TraceContextImpl.HandleEntityMissing(IAWSXRayRecorder recorder, Exception e, String message)
   at Amazon.XRay.Recorder.Handlers.EntityFramework.EFInterceptor.ProcessCommandError(CommandErrorEventData eventData)
   at Amazon.XRay.Recorder.Handlers.EntityFramework.EFInterceptor.CommandFailed(DbCommand command, CommandErrorEventData eventData)
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.CommandError(IDiagnosticsLogger`1 diagnostics, IRelationalConnection connection, DbCommand command, DbContext context, DbCommandMethod executeMethod, Guid commandId, Guid connectionId, Exception exception, DateTimeOffset startTime, TimeSpan duration)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteScalar(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Service.Start.Startup.InitializaDatabase(IApplicationBuilder app, ILogger`1 logger) in C:\Users\Service\Start\Startup.cs:line 795
   at Service.Start.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, ILogger`1 logger) in C:\Service\Start\Startup.cs:line 748
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)

**Comment by chazt3n** [comment]
So the littering of segments throughout the code is a tough pill to swallow for us. We have a microservices application with a common nuget package which is responsible for ensuring guaranteed delivery of SQS/SNS messages - services themselves hav many entry points that are not web requests. 

Is the Auto-Instrument agent a better option for us? 

I just need a way to get this deployed and we can have an ongoing effort

**Comment by lupengamzn** [comment]
Hey @chazt3n ,

When you're trying to trace the EF Core request, some initialization queries may be executed before a parent segment is created, which causes the `Entity doesn't exist in AsyncLocal` exception, can you double check in your code? Also, a repro would be very helpful if you can provide one.

If you don't feel like modifying your code, you may try the [auto instrumentation agent](https://github.com/aws/aws-xray-dotnet-agent) and instrument your application with X-Ray SDK out-of-box.

**Comment by chazt3n** [comment]
OK I definitely want to go the auto instrumentation route - I'm gonna be a customer for a long time so definitely do plan on contributing - I must prioritize getting to production with some visibility first!

My test setup is Xunit + In Memory Web api using Test Server + Create Client 

```csharp
        public static IApplicationBuilder UseMyCompanyXRay(this IApplicationBuilder builder, IWebHostEnvironment env,
            bool shouldEnableXrayLocally = false)
        {
            var logger = builder.ApplicationServices.GetService<ILogger<IApplicationBuilder>>();
            var config = builder.ApplicationServices.GetService<IConfiguration>();
            string xrayDaemonAddress = config.GetValue(XrayDaemonAddressEnvVar, DefaultXrayDaemonAddress);
            try
            {
                if (!env.IsDevelopment() || shouldEnableXrayLocally)
                {
                    AWSXRayRecorder recorder = new AWSXRayRecorderBuilder()
                        .WithDaemonAddress(xrayDaemonAddress)
                        .WithContextMissingStrategy(ContextMissingStrategy.LOG_ERROR)
                        .WithTraceContext()
                        .Build();
                    AWSXRayRecorder.InitializeInstance(recorder: recorder);
                    builder.UseXRay(config[ApplicationName]);
                }
            }
            catch (Exception exception)
            {
                logger.LogError(exception,
                    "Error Occurred Enabling AWS XRay. isDevelopmentEnvironment: {isDevelopmentEnvironment}, xrayDaemonAddress {xrayDaemonAddress}", env.IsDevelopment(), xrayDaemonAddress);
            }

            return builder;
        }
```

During test setup when creating the server, I call useStartup which calls that method. 

I'm running in a docker-compose and passing the env var + hardcoding missing context - I have no appsettings.json settings related to xray (intentionally, maybe a problem though)

I think you're making a lot of sense suggesting that since we're still IN startup when we hit this error, something's going on there.

But if I added a segment around the migration, it would succeed and I would get the error later in the test scenario.

**Comment by willarmiros** [comment]
Going to close this out in favor of the discussion in https://github.com/aws/aws-xray-dotnet-agent/issues/20, @chazt3n feel free to reopen if needed!
