### ISSUE TITLE
Unable to cast object of type '...FacadeSegment' to type '...Subsegment'

### ISSUE THREAD

**Issue by dr3x** [aws/aws-xray-sdk-dotnet#198]
Getting a cast error in Lambda execution; we're using a simple flow within a controller (Microsoft.AspNetCore.Mvc.ControllerBase):

```
_recorder.BeginSubsegment(nameof(MyController));
try {
...
}
catch (Exception ex)
{
_logger.LogError(ex, ...);
return Ok(CreateErrorResponse(...);
            }
finally {
_recorder.EndSubsegment();
}
```

Docs indicate that we need to call the .End* method for every .Begin* method; so I put the .End* call in a C# finally block to ensure it always gets invoked, even if an error gets caught and execution returns early.

Here _logger is the standard MS ILogger:
private readonly ILogger<MyController> _logger;

`Amazon.XRay.Recorder.Core.Exceptions.EntityNotAvailableException: Failed to cast the entity to Subsegment.
 ---> System.InvalidCastException: Unable to cast object of type 'Amazon.XRay.Recorder.Core.Internal.Entities.FacadeSegment' to type 'Amazon.XRay.Recorder.Core.Internal.Entities.Subsegment'.
   at Amazon.XRay.Recorder.Core.AWSXRayRecorder.PrepEndSubsegmentInLambdaContext()
   at Amazon.XRay.Recorder.Core.AWSXRayRecorder.ProcessEndSubsegmentInLambdaContext(Nullable`1 timestamp)
   at Amazon.XRay.Recorder.Core.AWSXRayRecorder.EndSubsegment(Nullable`1 timestamp)
   --- End of inner exception stack trace ---
   at Amazon.XRay.Recorder.Core.Internal.Context.TraceContextImpl.HandleEntityMissing(IAWSXRayRecorder recorder, Exception e, String message)
   at Amazon.XRay.Recorder.Core.AWSXRayRecorderImpl.HandleEntityNotAvailableException(EntityNotAvailableException e, String message)
   at Amazon.XRay.Recorder.Core.AWSXRayRecorder.EndSubsegment(Nullable`1 timestamp)
`

**Comment by srprash** [comment]
Hi, looks like the `BeginSubsegment` is failing to either create a subsegment or load it in the context. As a result, when `EndSubsegment` expects a subsegment to be present, it finds the root `FacadeSegment` instead.

Can you make sure that `nameof(MyController)` is not returning an empty string or null? Do you see any logs related to failure to begin a subsegment?
