### ISSUE TITLE
Exception thrown when hosting ASP.NET Core MVC application in lambda using Amazon.Lambda.AspNetCoreServer 

### ISSUE THREAD

**Issue by rnowosielski** [aws/aws-xray-sdk-dotnet#2]
I have a ASP.NET Core MVC application hosted inside of the lambda using the Amazon.Lambda.AspNetCoreServer

When I try to initialise the X-Ray I have the following exception when the app is starting up inside the lambda

    Unhandled Exception: System.AggregateException: One or more errors occurred. (Unable to cast object of type 'Amazon.XRay.Recorder.Core.Internal.Entities.FacadeSegment' to type 'Amazon.XRay.Recorder.Core.Internal.Entities.Subsegment'.) ---> System.InvalidCastException: Unable to cast object of type 'Amazon.XRay.Recorder.Core.Internal.Entities.FacadeSegment' to type 'Amazon.XRay.Recorder.Core.Internal.Entities.Subsegment'.
      at Amazon.XRay.Recorder.Core.AWSXRayRecorder.ProcessSubsegmentInLambdaContext(String name)
      at Amazon.XRay.Recorder.Core.AWSXRayRecorder.BeginSubsegment(String name)
      at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineHandler.ProcessBeginRequest(IExecutionContext executionContext)
      at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineHandler.<InvokeAsync>d__27`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext() in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 58

The exception seems to originate from the following method, where there is an assumption that if there and entity it for sure is a subsegment in lambda...

    private void ProcessSubsegmentInLambdaContext(string name)
        {
            if (!TraceContext.IsEntityPresent()) //No facade segment available and first subsegment of a subsegment branch needs to be added
            {
                AddFacadeSegment(name);
                AddSubsegmentInLambdaContext(new Subsegment(name));
            }
            else //continuation of subsegment branch
            {
                var parentSubsegment = (Subsegment)TraceContext.GetEntity();
                var environmentRootTraceId = TraceHeader.FromString(GetTraceVariablesFromEnvironment()).RootTraceId;
                if ((null != environmentRootTraceId) && !environmentRootTraceId.Equals(parentSubsegment.RootSegment.TraceId)) //If true, customer has leaked subsegments across invocation
                {
                    TraceContext.ClearEntity(); //reset TraceContext
                    BeginSubsegment(name); //This adds Facade segment with updated environment variables
                }
                else
                {
                    AddSubsegmentInLambdaContext(new Subsegment(name));
                }

            }
        }

however in my case it is simply not because this method gets called earlier

        private void BeforeRequestEventHandler(object sender, RequestEventArgs e)
        {
            var args = e as WebServiceRequestEventArgs;
            if (args == null)
            {
                _logger.DebugFormat("Failed to handle BeforeRequestEvent, because e can't be converted to WebServiceRequestEventArgs.");
                return;
            }

            if (TraceHeader.TryParse(TraceContext.GetEntity(), out TraceHeader traceHeader))
            {
                args.Headers[TraceHeader.HeaderKey] = traceHeader.ToString();
            }
            else
            {
                _logger.DebugFormat("Failed to inject trace header to AWS SDK request as the segment can't be converted to TraceHeader.");
            }
            _recorder.BeginSubsegment(RemoveAmazonPrefixFromServiceName(args.ServiceName));
            _recorder.SetNamespace("aws");
        }

and the call to `TraceContext.GetEntity()` in case of running in lambda initialises the entity to `FacadeSegment`

Can you let me know if I am maybe using these tools incorrectly or is it some sort of a bug?

**Comment by yogiraj07** [comment]
Hi @rnowosielski ,

Thank you for posting this issue.

From the error stack trace, I see that `XRayPipelineHandler` is invoked. This is a wrapper around your AWS SDK request (for eg: Dynamo db operations). I wonder how this `BeforeRequestEventHandler()` method is called since its a part of `AWSSdkTracingHandler ` class and is deprecated. Can you please confirm the location of your error.

Also please let me know how you have configured your app with X-Ray.
1) Have you configured your ASP.NET Core app with X-Ray using this way: [ASP.NET Core]( https://github.com/aws/aws-xray-sdk-dotnet/tree/master#aspnet-core-20-framework-net-core--nuget)

2) The sequence of call being made , is it the following :
[Deploying app to AWS Lambda] -> [Starting ASP.NET Core app] -> [Making AWS SDK Call]   
A sequence diagram may be helpful.

3) Are you creating any custom segment/subsegment within the app ?

Please let us know, this will help to understand your scenario.

Thanks,
Yogi

**Comment by rnowosielski** [comment]
I followed the steps for .NET Core to configure my app. So I do have a `app.UseXRay("Segment name");` in the `Configure` method, and then in the constructor of the `Startup` I placed               
 
    AWSXRayRecorder.InitializeInstance(Configuration) ;
    AWSSDKHandler.RegisterXRayForAllServices();

The peculiar thing is that I do have KMS calls in the `ConfigurServices` method that is decrypting the connection string for my database, so if I understand that correctly, the KMS calls will be reported at the very startup of the app even before any incoming request gets processed.

My work around for this problem was to surround the content of `ConfigureServices` method with additional subsegment and that fixed it for me, but I thought it would be useful to fix this scenario for others who might run into similar situations.

**Comment by AbbTek** [comment]
HI,

I'm getting a similar issue. In my case, I have a Lambda function running NetCore 2.0 and APIGateway. I'm starting the X-Ray in the handler 

AWSSDKHandler.RegisterXRayForAllServices();

`One or more errors occurred. (Unhandled exception): AggregateException
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

at Ansarada.Integrations.FileStore.Handlers.APIGateway.ApiHandler.ErrorHandler(Exception ex) in /ansarada/functions/services-api/src/dotnet/Ansarada.Integrations.FileStore.Handlers/APIGateway/ApiHandler.cs:line 23
at Lambda.SDK.Core.Handlers.APIGatewayHandler`1.<ConcreteProcessAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Lambda.SDK.Core.Handlers.BaseHandler`3.<ProcessAsync>d__2.MoveNext()
**Unable to cast object of type 'Amazon.XRay.Recorder.Core.Internal.Entities.FacadeSegment' to type 'Amazon.XRay.Recorder.Core.Internal.Entities.Subsegment'.: InvalidCastException**
at Amazon.XRay.Recorder.Core.AWSXRayRecorder.ProcessSubsegmentInLambdaContext(String name)
at Amazon.XRay.Recorder.Core.AWSXRayRecorder.BeginSubsegment(String name)
at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineHandler.ProcessBeginRequest(IExecutionContext executionContext)
at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller)
at Amazon.DynamoDBv2.DocumentModel.Table.DescribeTable(String tableName)
at Amazon.Runtime.Internal.Util.Cache`2.GetValueHelper(TKey key, Boolean& isStaleItem, Func`2 creator)
at Amazon.DynamoDBv2.DocumentModel.Table.LoadTableInfo()
at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetUnconfiguredTable(String tableName)
at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetTargetTable(ItemStorageConfig storageConfig, DynamoDBFlatConfig flatConfig, DynamoDBConsumer consumer)
at Amazon.DynamoDBv2.DataModel.DynamoDBContext.LoadHelper[T](Key key, DynamoDBFlatConfig flatConfig, ItemStorageConfig storageConfig, Boolean isAsync)
at Amazon.Runtime.Internal.AsyncRunner.<>c__DisplayClass1_2`1.<Run>b__1()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Amazon.Runtime.Internal.AsyncRunner.<>c__DisplayClass1_0`1.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Lambda.SDK.Core.AWS.DynamoDB.DynamoDBWrapper.<LoadAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Ansarada.Integrations.FileStore.Business.Core.FileStoreBusiness.<ListAsync>d__10.MoveNext() in /ansarada/functions/services-api/src/dotnet/Ansarada.Integrations.FileStore.Business/Core/FileStoreBusiness.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Ansarada.Integrations.FileStore.Handlers.APIGateway.Controllers.FileStoreController.<List>d__6.MoveNext() in /ansarada/functions/services-api/src/dotnet/Ansarada.Integrations.FileStore.Handlers/APIGateway/Controllers/FileStoreController.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Lambda.SDK.Core.Handlers.Controllers.ControllerRunner.<ProcessAPIGatewayController>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Lambda.SDK.Core.Handlers.APIGatewayHandler`1.<ConcreteProcessAsync>d__0.MoveNext()`

**Comment by yogiraj07** [comment]
Hi @rnowosielski , @AbbTek ,

Thank you for reporting this bug. We appreciate your efforts and are currently working on fix. We would soon update you.

Thanks,
Yogi

**Comment by yogiraj07** [comment]
Hi @rnowosielski , @AbbTek ,

We have fixed this bug in release : `2.0.1-beta`. Please feel free to explore new version. Let us know if you have questions.

Thanks,
Yogi

**Comment by AbbTek** [comment]
Hi @yogiraj07 I tested it, and now it works perfectly, thanks it is really cool
