### ISSUE TITLE
Path in tests assume Windows path separators

### ISSUE THREAD

**Issue by MrLarssonJr** [aws/aws-xray-sdk-dotnet#41]
Found `private static String _path = @"JSONs\AWSRequestInfo.json";` in `./sdk/test/UnitTests/AWSSdkTracingHandlerTests.cs`.

This seems to prevent me to run the tests on macOS. When I run the tests I get:
```
Amazon.XRay.Recorder.UnitTests.AWSSdkTracingHandlerTests.TestDynamoDbClient

Test method Amazon.XRay.Recorder.UnitTests.AWSSdkTracingHandlerTests.TestDynamoDbClient threw exception: 
System.IO.FileNotFoundException: Could not find file '/Users/jesperlarsson/RiderProjects/aws-xray-sdk-dotnet/sdk/test/UnitTests/bin/Debug/netcoreapp2.0/JSONs\AWSRequestInfo.json'.
    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineHandler..ctor(String path) in /Users/jesperlarsson/RiderProjects/aws-xray-sdk-dotnet/sdk/src/Handlers/AwsSdk/Internal/XRayPipelineHandler.cs:line 85
   at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineCustomizer.Customize(Type serviceClientType, RuntimePipeline pipeline) in /Users/jesperlarsson/RiderProjects/aws-xray-sdk-dotnet/sdk/src/Handlers/AwsSdk/Internal/XRayPipelineHandler.cs:line 651
   at Amazon.Runtime.Internal.RuntimePipelineCustomizerRegistry.ApplyCustomizations(Type type, RuntimePipeline pipeline) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\RuntimePipelineCustomizerRegistry.cs:line 108
   at Amazon.XRay.Recorder.UnitTests.AWSSdkTracingHandlerTests.TestDynamoDbClient() in /Users/jesperlarsson/RiderProjects/aws-xray-sdk-dotnet/sdk/test/UnitTests/AWSSdkTracingHandlerTests.cs:line 268
```

**Comment by yogiraj07** [comment]
Hi @MrLarssonJr ,
Thank you for PR. I have merged it.
