### ISSUE TITLE
Error when pulling secret using custom Manifest

### ISSUE THREAD

**Issue by sergedomk** [aws/aws-xray-sdk-dotnet#74]
Just pulled in 2.6.0 and got error attempting to pull secret from Secrets Manager.

I haven't researched this extensively yet, but it appears to be directly related to custom Manifest changes added in https://github.com/aws/aws-xray-sdk-dotnet/pull/63.

Given that I was responsible for this change, I feel I must apologize for not catching it.

Received the following error regardless of whether the custom manifest was added as a path or stream.

```
AmazonXRayClient 20|2019-04-22T09:10:01.942Z|ERROR|An exception of type HttpErrorResponseException was handled in ErrorHandler. --> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_mobile\HttpRequestMessageFactory.cs:line 539
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 175
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
AmazonXRayClient 21|2019-04-22T09:10:02.041Z|ERROR|AmazonSecretsManagerException making request GetSecretValueRequest to https://secretsmanager.us-east-1.amazonaws.com/. Attempt 1. --> Amazon.SecretsManager.AmazonSecretsManagerException: Missing Authentication Token ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_mobile\HttpRequestMessageFactory.cs:line 539
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 175
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\HttpErrorResponseExceptionHandler.cs:line 60
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 212
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 104
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointDiscoveryHandler.cs:line 79
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 98
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
```

Copying the default manifest and using that as a custom manifest still resulted in the error. Removing the loading of the custom manifest resulted in no error.

I got the error regardless of whether or not I had XRay tracing enabled.

**Comment by yogiraj07** [comment]
Hi @sergedomk ,
I can reproduce this issue locally and working on the fix. The issue lies in the way the [code](https://github.com/aws/aws-xray-sdk-dotnet/pull/63/files#diff-9f4840a8c388c0e3929a12615bdf65e2R675) was changed to single instance of `XRayPipelineHandler` and how `XRayPipelineCustomizer` is invoked by AWS SDK for each AWS SDK request. 

I wanted some more information on how you have done X-Ray instrumentation for AWS SDK calls.
1. How is your instrumentation code looks like w.r.t AWSSDKHandler? 
2. Whether single or multiple amazon service clients are instrumented with your app? For eg DynamoDb, S3 etc.
3. For the above stack trace, have you explicitly created `AmazonXRayClient` or this error originated as a result of pollers which asynchronously are running by the X-Ray SDK. Reason : I am wondering why XRayClient is talking to `AmazonSecretsManagerException` since X-Ray SDK XRayClient never uses credentials. 
4.   For the statement `I got the error regardless of whether or not I had XRay tracing enabled.` -> How did you disabled the X-Ray? Is it commenting the AWS SDK handler instrumentation or setting the boolean value to false in the appsettings.json file?

**Comment by sergedomk** [comment]
1. I'll try to illustrate with an example.

In NuGet package:

```
public static class AwsXRay
{
    private const string AwsWhitelistManifestResourceName = "MyNamespace.AwsWhitelistManifest.json";

    public static void InitializeInstance(IConfiguration configuration)
    {
        AWSXRayRecorder.RegisterLogger(Amazon.LoggingOptions.Console);
        AWSXRayRecorder.InitializeInstance(configuration);

        using (var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(AwsWhitelistManifestResourceName))
        {
            Amazon.XRay.Recorder.Handlers.AwsSdk.AWSSDKHandler.RegisterXRayManifest(stream);
        }
        Amazon.XRay.Recorder.Handlers.AwsSdk.AWSSDKHandler.RegisterXRayForAllServices();
    }

    public static void TraceSegment(Action method, string segment)
    {
        AWSXRayRecorder.Instance.BeginSegment(segment);
        try
        {
            method();
        }
        catch (Exception ex)
        {
            AWSXRayRecorder.Instance.AddException(ex);
            throw;
        }
        finally
        {
            AWSXRayRecorder.Instance.EndSegment();
        }
    }
}
```

In code:

```
// configure xray
AwsXRay.InitializeInstance(configuration);

AwsXRay.TraceSegment(() =>
{
    ... a bunch of code which includes a call to secrets manager ...
});
```

2. This particular code only talks to Secrets Manager. No other Amazon Services.

3. Have not explicitly created `AmazonXRayClient`. Guessing the reason for the stacktrace appearing as though it originates with XRay has something to do with that stacktrace being what was logged by the XRay SDK with debug logging to Console enabled. The exception raised in the containing code looks more like this:

````
09:10:02.0997 ERROR (My.Application) One or more errors occurred. (Missing Authentication Token)    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at My.Package.DoSecretStuff.GetSecret()
   at My.Application.DoStuff.GetSomething() in C:\######
   at My.Application.DoStuff.DoSomething() in C:\######
   at My.Application.DoSomethingElse() in C:\######
   at My.Application.DoSomething() in C:\#######
   at My.Application.<Run>b__15_0() in C:\#######
   at HigherLogic.XRay.AwsXRay.TraceSegment(Action method, String segment)
   at My.Application.Run() in C:\#######
````

4. I disabled tracing by setting the boolean in appsettings.json:

````
"DisableXRayTracing": true
````

**Comment by yogiraj07** [comment]
Hi @sergedomk ,
We have releases `V2.6.1`. Please refer [Changelog](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/CHANGELOG.md) for details. 

Feel free to reopen the issue if you face any problem.

Thanks,
Yogi

**Comment by sergedomk** [comment]
Thanks for the quick fix!

I confirmed that I can register a manifest both by path and stream successfully now.
