### ISSUE TITLE
Amazon.XRay.AmazonXRayException: The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by okubiak** [aws/aws-xray-sdk-dotnet#79]
Hello,

I have a random exception on GetSamplingTargetsRequest:
```
ERROR Amazon.XRay.AmazonXRayClient - An exception of type HttpErrorResponseException was handled in ErrorHandler.
Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
ERROR Amazon.XRay.AmazonXRayClient - AmazonXRayException making request GetSamplingTargetsRequest to http://172.17.0.1:2000/. Attempt 1.
Amazon.XRay.AmazonXRayException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
--- End of inner exception stack trace ---
at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
ERROR Amazon.XRay.Recorder.Core.Sampling.TargetPoller - Encountered exception while polling targets
Amazon.XRay.AmazonXRayException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
--- End of inner exception stack trace ---
at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.XRay.Recorder.Core.Sampling.ServiceConnector.GetSamplingTargets(List`1 rules)
at Amazon.XRay.Recorder.Core.Sampling.TargetPoller.RefreshTargets()
at Amazon.XRay.Recorder.Core.Sampling.TargetPoller.Start(Object state)
```

Is it a known issue??
It happened once this night, but I've already seen it.

Regards

**Comment by yogiraj07** [comment]
@okubiak ,
This is the [code](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/Sampling/TargetPoller.cs#L66) you are hitting. 

Can you get more details:
1. Do you see this error frequently or its intermittent? 
2. What are the versions of AWSXRayRecorder nuget packages ? Can you use the latest? We had previously reported some similar [issue](https://github.com/aws/aws-xray-sdk-dotnet/issues/74) 
3. Are you using AWS SDK handler? How are you instrumenting it. 
4. What is your environment stack look like ? Framework and general flow / calls instrumented? 

Best,
Yogi

**Comment by okubiak** [comment]
Sorry I forgot to give you precious info :(

1. It's intermittent, like I got it only twice (well I've seen it twice but maybe I got it more than that). The latest occurence was in the middle of the night...
2. I'm already using the latest version, 2.6.1
3. About the handler I'm doing a simple `AWSSDKHandler.RegisterXRayForAllServices();`
```
AWSXRayRecorder.RegisterLogger(LoggingOptions.Log4Net);
AWSXRayRecorder.InitializeInstance(_configuration);
AWSSDKHandler.RegisterXRayForAllServices();
```
Here is the configuration btw:
```
"XRay": {
    "DisableXRayTracing": "false",
    "AWSXRayPlugins": "EC2Plugin, ECSPlugin",
    "UseRuntimeErrors": "true"
},
```
4. Don't really know what you need. It happened on an ASP.Net Core 2.1 application in docker.
I also have some background tasks which are instrumented in a new Segment for each loop (but it seems that it's not working fine for now... but it's not the purpose of this issue)

**Comment by yogiraj07** [comment]
@okubiak ,
Thanks for the details.
X-Ray client never uses credentials to make a request : [reference](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/Sampling/ServiceConnector.cs#L39). It sends unsigned request to X-Ray daemon over TCP and the X-Ray daemon signs these request on your behalf using the X-Ray daemon credentials and send it to X-Ray service. The daemon serves as a reverse proxy and returns response to the X-Ray SDK. 

I cannot reproduce this case locally. But my best guess is there is something related to X-Ray daemon not running for a small moment or a network blip while making a request. It is also possible if there is any credential rotation for the AWS account user during same time. You can check X-Ray daemon log during same time and see whether the daemon has logged any error message over TCP in the xray.log file : [reference](https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon.html)

However, these pollers are asynchronous and the error stack doesn't affect your tracing capabilities.

**Comment by yogiraj07** [comment]
Hi @okubiak,
Please feel free to re-open this if you are still facing this issue.
